data_config:
  price_column: 'close'
  volume_column: 'volume'
  datetime_column: 'timestamp'
  timeframe: '15m'

features_config:
  technical_indicators:
    - name: rsi
      params:
        timeperiod: 14
    - name: macd
      params:
        fastperiod: 12
        slowperiod: 26
        signalperiod: 9
    - name: stoch
      params:
        fastk_period: 14
        slowk_period: 3
        slowd_period: 3
    - name: atr
      params:
        timeperiod: 14
    - name: bbands
      params:
        timeperiod: 20
        nbdevup: 2
        nbdevdn: 2
    - name: obv
      params: {}
    - name: vwap
      params:
        window: 20
    - name: adx
      params:
        timeperiod: 14
  
  returns:
    type: 'statistical'
    params:
      window: [1, 5, 10, 20]
      type: 'pct'
  volatility:
    type: 'statistical'
    params:
      window: [10, 20, 50]
      type: 'realized'
  zscore:
    type: 'statistical'
    params:
      window: 20
      columns: ['close', 'volume', 'rsi_14', 'macd', 'atr_14']
  temporal:
    type: 'datetime'
    params:
      features:
        - 'hour'
        - 'weekday'
        - 'month'
        - 'is_weekend'
        - 'session_progress'

model_config:
  ensemble:
    models:
      - name: long
        params:
          n_estimators: 1000
          max_depth: 4
          learning_rate: 0.01
          min_child_weight: 5
          subsample: 0.8
          colsample_bytree: 0.8
          gamma: 0.2
          objective: 'binary:logistic'
          eval_metric: ['auc', 'error']
          scale_pos_weight: 5.0
          early_stopping_rounds: 50
          reg_alpha: 0.1
          reg_lambda: 1.0
      - name: short
        params:
          n_estimators: 1000
          max_depth: 4
          learning_rate: 0.01
          min_child_weight: 5
          subsample: 0.8
          colsample_bytree: 0.8
          gamma: 0.2
          objective: 'binary:logistic'
          eval_metric: ['auc', 'error']
          scale_pos_weight: 5.0
          early_stopping_rounds: 50
          reg_alpha: 0.1
          reg_lambda: 1.0
    threshold: 0.7
    min_probability: 0.75
    use_smote: true
    class_weight: 'balanced'
    position_sizing:
      base_size: 1.0
      confidence_multiplier: 0.75
      max_size: 1.5
      volatility_adjustment: true
  selected_features:
    # Volatility Features
    - 'atr_14'
    - 'volatility_10'
    - 'volatility_ratio'
    # Trend Features
    - 'trend_strength'
    - 'trend_direction'
    - 'bb_breakout'
    # Volume Features
    - 'volume_ratio'
    - 'volume_trend'
    - 'volume_trend_confirm'
    # Momentum Features
    - 'rsi_14'
    - 'macd_histogram'
    - 'stoch_k'
    # Price Action Features
    - 'vwap_distance'
    - 'return_1'
    - 'return_5'
    - 'return_10'
    # Statistical Features
    - 'zscore_volume_20'
    - 'zscore_rsi_14_20' 
  prediction:
    threshold: 0.7
    min_prediction_confidence: 0.75 