data_config:
  price_column: 'close'
  volume_column: 'volume'
  datetime_column: 'timestamp'
  timeframe: '15m'

features_config:
  # Technical indicators
  rsi:
    type: 'technical'
    params:
      window: 14
  macd:
    type: 'technical'
    params:
      fast: 12
      slow: 26
      signal: 9
  stoch:
    type: 'technical'
    params:
      k_window: 14
      d_window: 3
  atr:
    type: 'technical'
    params:
      window: 14
  bbands:
    type: 'technical'
    params:
      window: 20
      num_std: 2
  obv:
    type: 'technical'
  vwap:
    type: 'technical'
    params:
      window: 20
  adx:
    type: 'technical'
    params:
      window: 14
  
  # Statistical features
  returns:
    type: 'statistical'
    params:
      window: [1, 5, 10, 20]
      type: 'pct'
  volatility:
    type: 'statistical'
    params:
      window: [10, 20, 50]
      type: 'realized'
  zscore:
    type: 'statistical'
    params:
      window: 20
      columns: ['close', 'volume', 'rsi_14', 'macd', 'atr_14']
  
  # Temporal features
  temporal:
    type: 'datetime'
    params:
      features:
        - 'hour'
        - 'weekday'
        - 'month'
        - 'is_weekend'
        - 'session_progress'

model_config:
  long_model:
    model_params:
      n_estimators: 1000
      max_depth: 8
      learning_rate: 0.01
      min_child_weight: 3
      subsample: 0.8
      colsample_bytree: 0.8
      gamma: 0.1
      objective: 'binary:logistic'
      eval_metric: ['auc', 'error']
      scale_pos_weight: 1.5
      early_stopping_rounds: 50
      reg_alpha: 0.05
      reg_lambda: 0.5
    threshold: 0.40
    min_probability: 0.45
    use_smote: true
    class_weight: 'balanced'
    position_sizing:
      base_size: 1.0
      confidence_multiplier: 0.5
      max_size: 2.0
      volatility_adjustment: true
    risk_management:
      max_drawdown: 0.02
      stop_loss: 0.015
      take_profit: 0.03
      trailing_stop: true
      trailing_stop_distance: 0.008
      max_holding_periods: 48
      profit_taking_adjustment: true
  
  short_model:
    model_params:
      n_estimators: 1000
      max_depth: 8
      learning_rate: 0.01
      min_child_weight: 3
      subsample: 0.8
      colsample_bytree: 0.8
      gamma: 0.1
      objective: 'binary:logistic'
      eval_metric: ['auc', 'error']
      scale_pos_weight: 1.5
      early_stopping_rounds: 50
      reg_alpha: 0.05
      reg_lambda: 0.5
    threshold: 0.40
    min_probability: 0.45
    use_smote: true
    class_weight: 'balanced'
    position_sizing:
      base_size: 1.0
      confidence_multiplier: 0.5
      max_size: 2.0
      volatility_adjustment: true
    risk_management:
      max_drawdown: 0.02
      stop_loss: 0.015
      take_profit: 0.03
      trailing_stop: true
      trailing_stop_distance: 0.008
      max_holding_periods: 48
      profit_taking_adjustment: true
  
  selected_features:
    # Base features
    - 'hour'
    - 'weekday'
    - 'month'
    - 'is_weekend'
    - 'session_progress'
    # Technical indicators
    - 'rsi_14'
    - 'macd'
    - 'macd_signal'
    - 'macd_histogram'
    - 'stoch_k'
    - 'stoch_d'
    - 'atr_14'
    - 'bb_upper'
    - 'bb_middle'
    - 'bb_lower'
    - 'bb_breakout'
    - 'obv'
    - 'vwap'
    - 'vwap_distance'
    # Market Regime Features
    - 'ema_20'
    - 'ema_50'
    - 'ema_200'
    - 'price_ema_20_ratio'
    - 'price_ema_50_ratio'
    - 'price_ema_200_ratio'
    - 'trend_strength'
    - 'trend_direction'
    - 'volatility_regime'
    - 'volatility_ratio'
    - 'volume_ratio'
    - 'volume_trend_confirm'
    - 'rsi_divergence'
    - 'efficiency_ratio'
    - 'zscore_price'
    - 'trend_exhaustion'
    # Pattern Recognition
    - 'pattern_3blackcrows'
    - 'pattern_3whitesoldiers'
    - 'pattern_engulfing'
    - 'pattern_harami'
    - 'pattern_morningstar'
    - 'pattern_eveningstar'
    # Support/Resistance
    - 'price_to_support'
    - 'price_to_resistance'
    # Returns and volatility
    - 'return_1'
    - 'return_5'
    - 'return_10'
    - 'return_20'
    - 'volatility_10'
    - 'volatility_20'
    - 'volatility_50'
    # Z-scores
    - 'zscore_close_20'
    - 'zscore_volume_20'
    - 'zscore_rsi_14_20'
    - 'zscore_macd_20'
    - 'zscore_atr_14_20' 